//American Standard Code for Information Interchange//
//It was a form of displaying pictures before pictures could actually be downloaded.//

println ("                      _..._");
println ("                     //MMMMM\\");
println ("                    CI8H#H8ID");
println ("                    CI8H#H8ID");
println ("                     \\WWWWW// ");
println ("                       I._.I");
println ("                       I._.I");
println ("                       I._.I");
println ("                       I._.I");
println ("                       I._.I");
println ("                       I._.I");
println ("                       I._.I");
println ("                       I.,.I");
println ("                       //#\\ ");
println ("                    .dH# # #Hb.");
println ("                _.~d#XXP I 7XX#b~,_");
println ("             _.dXV^XP^ Y X Y ^7X^VXb._ ");
println ("            /AP^  \\PY   Y   Y7//  ^VA\\");
println ("           /8/     \\PP  I  77//    \\8\\");
println ("          /J/        IV     VI       \\L\\ ");
println ("          L|         |  \\ //  |         |J");
println ("          V          |  |  |  |          V");
println ("                     |  |  |  |");
println ("                     |  |  |  |");
println ("                     |  |  |  |");
println ("                     |  |  |  |");
println ("  _                  |  |  |  |                  _");
println (" ( \\                |  |  |  |                 / )");
println ("  \\ \\              |  |  |  |                / /");
println (" ('\\ \\             |  |  |  |               / /`)");
println ("  \\ \\ \\           |  |  |  |              / / /");
println (" ('\\ \\ \\          |  |  |  |             / / /`)");
println ("  \\ \\ \\ )         |  |  |  |            ( / / /");
println (" ('\\ \\( )          |  |  |  |            ( )/ /`)");
println ("  \\ \\ ( |          |  |  |  |            | ) / /");
println ("   \\ \\( |          |  |  |  |            | )/ /");
println ("    \\ ( |           |  |  |  |            | ) /");
println ("     \\( |           |    V   |            | )/");
println ("      | |            |    |   |            | |");
println ("      J | ___...~~--'|    |   |`--~~...___ | L");
println ("      >-+<...___     |    |   |     ___...>+-<");
println ("     /     __   `--~.L___L___J.~--'   __     \\");
println ("     K    /  ` --.     d===b     .-- '  \\   H");
println ("    \\_._/       \\   // I \\   /       \\_._/");
println ("       `--~.._    \\__\\ I //__/     _..~--'");
println ("              `--~~..____ ____..~~--'");
println ("                     |   T   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     |   |   |");
println ("                     I   '   I");
println ("                     \\     /");
println ("                      \\   /");
println ("                       \\ /");
